<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Application extends Model
{
    use HasFactory;

    protected $guarded = [];

    protected $keyType = 'string';

    public $incrementing = false;

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function ($model) {
            $model->id = \Illuminate\Support\Str::uuid();
        });
    }

    public function getShortDescriptionAttribute()
    {
        // if description is longer than 100 characters, cut it and add '...' at the end
        return strlen($this->description) > 100 ? substr($this->description, 0, 100).'...' : $this->description;
    }

    public function owner()
    {
        return $this->belongsTo(\App\Models\User::class);
    }

    public function clients()
    {
        return $this->hasMany(\App\Models\Client::class);
    }
}
