name: Build and Push Docker Image (Multi-Arch)

on:
  release:
    types: [published]

jobs:
  build:
    strategy:
      matrix:
        include:
          - name: amd64
            os: ubuntu-latest
            platform: linux/amd64
          - name: arm64
            os: ubuntu-24.04-arm
            platform: linux/arm64

    name: Build and Push (${{ matrix.name }})
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Bestimme das vollständige Image (namespace/repo) für Docker Hub
      - name: Resolve Docker Hub image name
        id: image
        shell: bash
        run: |
          if [ -n "${{ secrets.DOCKERHUB_REPO }}" ]; then
            echo "name=${{ secrets.DOCKERHUB_REPO }}" >> "$GITHUB_OUTPUT"
          else
            # Fallback: <DOCKERHUB_USERNAME>/<github repo name>, alles lowercase
            REPO_LOWER=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')
            echo "name=${{ secrets.DOCKERHUB_USERNAME }}/${REPO_LOWER}" >> "$GITHUB_OUTPUT"
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: docker.io/${{ steps.image.outputs.name }}

      - name: Build and push Docker image (${{ matrix.platform }})
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ matrix.platform }}
          push: true
          tags: docker.io/${{ steps.image.outputs.name }}:${{ github.event.release.tag_name }}-${{ matrix.name }}
          labels: ${{ steps.meta.outputs.labels }}
          provenance: false
          sbom: false

  merge-manifest:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Resolve Docker Hub image name
        id: image
        shell: bash
        run: |
          if [ -n "${{ secrets.DOCKERHUB_REPO }}" ]; then
            echo "name=${{ secrets.DOCKERHUB_REPO }}" >> "$GITHUB_OUTPUT"
          else
            REPO_LOWER=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')
            echo "name=${{ secrets.DOCKERHUB_USERNAME }}/${REPO_LOWER}" >> "$GITHUB_OUTPUT"
          fi

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create and push multi-arch manifest
        run: |
          docker buildx imagetools create \
            --tag docker.io/${{ steps.image.outputs.name }}:latest \
            --tag docker.io/${{ steps.image.outputs.name }}:${{ github.event.release.tag_name }} \
            docker.io/${{ steps.image.outputs.name }}:${{ github.event.release.tag_name }}-amd64 \
            docker.io/${{ steps.image.outputs.name }}:${{ github.event.release.tag_name }}-arm64
