name: Build and Push Docker Image (Multi-Arch)

on:
  release:
    types: [published]

jobs:
  build:
    strategy:
      matrix:
        include:
          - name: amd64
            os: ubuntu-latest
            platform: linux/amd64
          - name: arm64
            os: ubuntu-24.04-arm
            platform: linux/arm64

    name: Build and Push (${{ matrix.name }})
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Format repository slug
        id: repo_slug
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: return github.repository.toLowerCase()

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ steps.repo_slug.outputs.result }}

      - name: Build and push Docker image (${{ matrix.platform }})
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ matrix.platform }}
          push: true
          tags: ghcr.io/${{ steps.repo_slug.outputs.result }}:${{ github.event.release.tag_name }}-${{ matrix.name }}
          labels: ${{ steps.meta.outputs.labels }}
          provenance: false
          sbom: false

  merge-manifest:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Format repository slug
        id: repo_slug
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: return github.repository.toLowerCase()

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and push multi-arch manifest
        run: |
          docker buildx imagetools create \
            --tag ghcr.io/${{ steps.repo_slug.outputs.result }}:latest \
            --tag ghcr.io/${{ steps.repo_slug.outputs.result }}:${{ github.event.release.tag_name }} \
            ghcr.io/${{ steps.repo_slug.outputs.result }}:${{ github.event.release.tag_name }}-amd64 \
            ghcr.io/${{ steps.repo_slug.outputs.result }}:${{ github.event.release.tag_name }}-arm64
