name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6 # or alternative dependency management
      with:
        php_version: '8.3'
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Install npm
      run: npm install
    - name: Build npm
      run: npm run build
#    - name: Execute tests (Unit and Feature tests) via PHPUnit
#      env:
#        DB_CONNECTION: sqlite
#        DB_DATABASE: database/database.sqlite
#      run: vendor/bin/phpunit
    - uses: php-actions/phpstan@v3
      with:
        path: app/
    - name: Run Enlightn Checks and Trigger the Enlightn Bot
      if: ${{ github.event_name == 'pull_request' }}
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
        ENLIGHTN_GITHUB_REPO: ${{ github.repository }}
      run: |
        cp .env.example .env
        php artisan enlightn --ci  --review --issue=${{ github.event.number }}

    - name: Run Pint
      if: ${{ github.event_name == 'pull_request' }}
      run: vendor/bin/pint

    - name: Commit linted files
      if: ${{ github.event_name == 'pull_request' }}
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Fixes coding style"

